### ISSUE TITLE
targetSdk 34 is failing

### ISSUE THREAD

**Issue by kumarmanishc** [calvinckho/capacitor-jitsi-meet#113]
Hello Team,

Thank you for this Awesome plugin.

**This is working fine for target sdk 33 but when we update target sdk 34 for Android 14 It's giving error**

```
2024-07-17 19:16:17.176  6992-6992  JitsiMeetSDK            org.example.app                    E  JitsiMeetUncaughtExceptionHandler FATAL ERROR
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.example.app/org.example.app.MainActivity}: java.lang.SecurityException: org.example.app: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4031)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4181)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:144)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2643)
                                                                                                    	at android.os.Handler.dispatchMessag
[7:22](https://kcssinfotech.slack.com/archives/D05TR02QMCN/p1721224348150039)
```

**We tried following as suggestions**:

The error message suggests that your broadcast receiver declaration in the `AndroidManifest.xml` file needs to explicitly state whether the receiver is exported or not, a requirement starting from Android 12 (API level 31).
To resolve this, you need to update your `AndroidManifest.xml` by adding either `android:exported="true"` or `android:exported="false"` to your broadcast receiver definition. Here’s an example of how you can do this:
### Example 1: Exported Receiver
If your broadcast receiver is intended to be accessible by other applications, you should set `android:exported` to `true`.
```xml
<receiver
    android:name=".YourBroadcastReceiver"
    android:exported="true">
    <intent-filter>
        <action android:name="your.intent.action" />
    </intent-filter>
</receiver>
```
But no luck

**Comment by kcss-ashvini** [comment]
I'm also experiencing the same issue
@calvinckho Any of guidance or update would be highly appreciated as 
according to change in google play policy we have to updated targetsdk as 34 before 31st August

**Comment by calvinckho** [comment]
Thanks for reporting this issue. I will try to take a look this week.

**Comment by calvinckho** [comment]
@kumarmanishc and @kcss-ashvini, are you two still using Capacitor 5? If yes, can you try to install the latest branch #capacitor-5 using the following command and report if the error message goes away?

`npm i git+ssh://git@github.com:calvinckho/capacitor-jitsi-meet#capacitor-5`

**Comment by calvinckho** [comment]
@kumarmanishc @kcss-ashvini, any update?

**Comment by kumarmanishc** [comment]
@calvinckho Yes I will update you by today evening.
Also is this change only available via GitHub or May I also install via npm registry?

**Comment by kumarmanishc** [comment]
@calvinckho Yes it seems to be working. Thank you

**Comment by kcss-ashvini** [comment]
@calvinckho Thank you. It's working for me as well.

**Comment by calvinckho** [comment]
Sounds great. capacitor-jitsi-meet@5.1.0 is released and I will close this issue.
